### ISSUE TITLE
建议可以自定义同步时间

### ISSUE THREAD

**Issue by shmily1866** [907739769/xiaoya-sync#3]
不知是否最近用的人太多了，早六晚六自动同步时，日志会抛出大量503的报错，导致有些剧同步不过来还得手动一下。同步的域名都加到直连规则里了，应该不是网的事

[2024-06-25 06:01:20:302] 
java.lang.RuntimeException: null
	at cn.jackding.xiaoyasync.SyncService.fetchFileList(SyncService.java:293) ~[classes!/:0.0.1-SNAPSHOT]
	at cn.jackding.xiaoyasync.SyncService.syncFilesRecursively(SyncService.java:132) ~[classes!/:0.0.1-SNAPSHOT]
	at cn.jackding.xiaoyasync.SyncService.lambda$null$1(SyncService.java:163) ~[classes!/:0.0.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_412]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_412]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_412]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_412]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_412]
[2024-06-25 06:01:20:302] <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

[2024-06-25 06:01:20:303] 第3次获取https://emby-data.tmxy.pp.ua/每日更新/电视剧/美剧/Monarch Legacy of Monsters (2023)/还是失败，放弃

但是手动通过tg发送命令更新时基本不会报错，不知道是同一时间同步的人太多的原因，还是爬虫的问题。

希望可以自定义同步时间，同时为了减轻服务器压力，设置间隔12小时的要求

**Comment by shmily1866** [comment]
😂😂😂早起六点自动同步还是报大量503，手动一次还是报大量503，在手动一次才正常。可能是服务器的问题，我指定域名试试吧

**Comment by 907739769** [comment]
自定义重启docker就行
